export const TS_LANGSERVICE_EXPECT_DIAGNOSTIC_ERROR_CODE = 50555;
export const EXPECT_KEYWORDS = [
  "toBeDefined",
  "toBe",
  "toBeCloseTo",
  "toBeFalsy",
  "toBeGreaterThan",
  "toBeGreaterThanOrEqual",
  "toBeLessThan",
  "toBeLessThanOrEqual",
  "toBeNaN",
  "toBeNull",
  "toBeTruthy",
  "toBeUndefined",
  "toContain",
  "toContainEqual",
  "toEqual",
  "toHaveLength",
  "toHaveProperty",
  "toMatchObject",
  "toStrictEqual",
  "toThrow",
];
